[context.production]
  command = "yarn build && cp .netlify/_headers public/_headers"
  publish = "public/"

[context.deploy-preview]
  command = "yarn build && cp .netlify/_headers public/_headers"
  publish = "public/"

[context.develop]
  command = "yarn build && cp .netlify/_headers public/_headers"
  publish = "public/"
